### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by nihcompmed** [mlgig/mrsqm#4]
Build fails because gcc has an unknown argument??

Processing /Users/vipulp/Downloads/mrsqm-main/mrsqm
Building wheels for collected packages: mrsqm
  Building wheel for mrsqm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/vipulp/opt/anaconda3/envs/timeseries/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1p/jk19lf1541j7wft_wfmc69wc0000gr/T/pip-req-build-dq2fhl0_/setup.py'"'"'; __file__='"'"'/private/var/folders/1p/jk19lf1541j7wft_wfmc69wc0000gr/T/pip-req-build-dq2fhl0_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/1p/jk19lf1541j7wft_wfmc69wc0000gr/T/pip-wheel-7sxl9is0
       cwd: /private/var/folders/1p/jk19lf1541j7wft_wfmc69wc0000gr/T/pip-req-build-dq2fhl0_/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'mrsqm' extension
  creating build
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/sfa
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/vipulp/opt/anaconda3/envs/timeseries/include -arch x86_64 -I/Users/vipulp/opt/anaconda3/envs/timeseries/include -arch x86_64 -I/Users/vipulp/opt/anaconda3/envs/timeseries/include/python3.7m -c mrsqm_wrapper.cpp -o build/temp.macosx-10.9-x86_64-3.7/mrsqm_wrapper.o -Wall -Ofast -g -std=c++11 -mfpmath=both -ffast-math
  error: unknown FP unit 'both'
  error: command 'gcc' failed with exit status 1

**Comment by lnthach** [comment]
Hi,
remove -mfpmath=both (in setup.py) should work.
