### ISSUE TITLE
module 'mrsqm' has no attribute 'MrSQMClassifier'

### ISSUE THREAD

**Issue by MZeinab** [mlgig/mrsqm#5]
module 'mrsqm' has no attribute 'MrSQMClassifier'   when running : clf = mrsqm.MrSQMClassifier().fit(X_train,y_train)

**Comment by heerme** [comment]
Hi,

You need to first install mrsqm in your local or your virtual Python environment, to be able to use it.
Please follow the instructions on the homepage under Installation and also check past Issues if you get errors.

Best wishes,
Georgiana.
