### ISSUE TITLE
Best Parameters on UCR-Datasets

### ISSUE THREAD

**Issue by patrickzib** [mlgig/mrsqm#6]
Hi, great work!  :) 

I am having problems to set the best hyper-parameters for the UCR-datasets.

Currently, the default-parameters seem to be optimized for speed, but the accuracy is rather low (measured on my hardware)

> Total mean-accuracy: 0.814
> Total fit_time: 3257.89
> Total pred_time: 1965.34

What would be the best set of parameters to obtain get results from the paper? In the paper this is referred to as `MrSQM_SFA_k5`.

**Comment by lnthach** [comment]
Hi Patrick,

Thank you for your interest. In the paper we set nsax = 0 and nsfa = 5 and default values for the remaining parameters. We find this the most balanced configuration in our experiments: not slow and good accuracy. Increasing nsfa (>5) can improve the overall accuracy a little but it is not worth the cost of speed in our opinion.

**Comment by patrickzib** [comment]
Hi Thach, 

great, thank you :) I was not sure how to translate SFA_k5 into nsax and nsfa. Your answer solved it.
